
- name: install software-properties-common
  apt:
    name: software-properties-common 

- name: add glusterfs repository
  apt_repository:
    repo: ppa:gluster/glusterfs-6

- name: install gluster
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - glusterfs-server
    - glusterfs-client

- name: start and enable grusterd
  service:
    name: glusterd
    state: started
    enabled: yes

- name: create gluster brick directory
  file:
    path: /postgres_brick
    state: directory

- name: create gluster share
  file:
    path: /postgres_data
    state: directory

- name: connect to gluster peers
  shell: "gluster peer probe {{ item }}"
  failed_when: false
  with_items: groups.servers

- name: create gluster volume
  gluster_volume:
    state: present
    name: postgres_volume
    bricks: /postgres_brick
    rebalance: yes
    force: yes
    replicas: "{{ groups['servers'] | length }}"
    cluster: "{{ groups.servers | join(',')}}"
  run_once: true
  failed_when: false

- name: mount gluster
  mount:
    path: /postgres_data
    src: "{{ inventory_hostname }}:/postgres_volume"
    fstype: glusterfs
    opts: _netdev
    state: mounted

