
- name: install pre dependencies
  apt:
    name: software-properties-common

- name: add glusterfs repository
  apt_repository:
    repo: ppa:gluster/glusterfs-6

- name: install gluster
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - glusterfs-server
    - glusterfs-client

- name: start and enable grusterd
  service:
    name: glusterd
    state: started
    enabled: yes

- name: create gluster brick directory
  file:
    path: /postgres_brick
    state: directory

- name: create gluster brick directory
  file:
    path: /postgres_data
    state: directory

- name: connect to gluster peers
  shell: "gluster peer probe {{ item }}"
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  failed_when: false
  with_items: groups.servers
  # when: "'Volume Name: gluster' not in gluster_volume_info.stdout"


- name: create gluster volume
  gluster_volume:
    state: present
    name: postgres_brick
    bricks: /postgres_brick
    rebalance: yes
    force: yes
    replicas: "{{ groups['servers'] | length }}"
    cluster: "{{ groups.servers | join(',')}}"
  run_once: true
  ignore_errors: yes
  #  with_items: "{{ groups['servers'] }}"

- name: mount gluster
  mount:
    path: /postgres_data
    src: "{{ inventory_hostname }}:/postgres_brick"
    fstype: glusterfs
    opts: _netdev
    state: mounted



